#!/bin/sh

version=0.14.12
minecraft_version=1.18.2
installer_version=0.11.1

if [ ! -z  $(ls /etc/minecraft/config) ]; then
   echo "Kubernetes Minecraft Configuration found. Copying over..."
   cp -vRf /etc/minecraft/config /minecraft
else
   echo "No configuration found, using default settings."
fi

dumb-init sh -c $1