#!/bin/sh

version=0.14.12
minecraft_version=1.18.2
installer_version=0.11.1

if [ ! -z  $(ls /etc/minecraft/config) ]; then
   echo "Kubernetes Minecraft Configuration found. Copying over..."
   cp -vRf /etc/minecraft/config /minecraft
else
   echo "No configuration found, using default settings."
fi

/bin/sh -c "java -Xmx2G -jar ./fabric-server-mc.${minecraft_version}-loader.${version}-launcher.${installer_version}.jar nogui"