name: Docker Image Test Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t my-image-name:$(date +%s) -f fabric.dockerfile .
