name: Docker Image Test Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME -f fabric.dockerfile --push .
